### ISSUE TITLE
Update cool_date_picker

### ISSUE THREAD

**Issue by ihsanturk2023** [joo6077/cool_datepicker#8]
i really like cool_date_picker and use it all my projects. Please update cool_date_picker. 
i getting below error:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':cool_datepicker' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by joo6077** [comment]
I've been working on this project to refactor old code. Please give me more time. It will take a few weeks.
Thank you for enjoying this library!
